name: "Mark/Close Stale Issues/PRs"
on:
  schedule:
  - cron: "* */1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |-
          This issue is stale because it has been open 180 days with no activity. Remove stale label or comment on the issue or it will be closed in 30 days.
        stale-pr-message: |-
          This pull request is stale because it has been open 180 days with no activity. Remove stale label or comment on the pull request or it will be closed in 30 days.
        days-before-stale: 0
        days-before-close: 30
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
